In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.2.2'

In [3]:
url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv"
laptops_df = pd.read_csv(url)

In [4]:
laptops_df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [5]:
#How many laptop brands are presented in the dataset?
amount = laptops_df.shape[0]
print(f"Number of laptop brands are: {amount}")

Number of laptop brands are: 2160


In [6]:
len(laptops_df)

2160

In [7]:
#How many laptop brands are presented in the dataset?
brands = laptops_df['Brand'].nunique()
print(f"Number of unique laptop brands: {brands}")

Number of unique laptop brands: 27


In [8]:
#How many columns in the dataset have missing values?
missing_values = laptops_df.isnull().sum()

columns_with_missing = missing_values[missing_values > 0]

num_columns_with_missing = len(columns_with_missing)
print(f"Number of columns with missing values: {num_columns_with_missing}")

Number of columns with missing values: 3


In [9]:
#What's the maximum final price of Dell notebooks in the dataset?
max_price_dell = laptops_df[laptops_df['Brand'] == 'Dell']['Final Price'].max()
print(f"The maximum final price of Dell notebooks is: ${max_price_dell:.2f}")

The maximum final price of Dell notebooks is: $3936.00


In [10]:
median_value = laptops_df['Screen'].median()
print(f"the median value of screen is: {median_value}")

the median value of screen is: 15.6


In [11]:
most_frequent_value = laptops_df['Screen'].mode()[0]
print(f"The most frequent value in the Screen column is: {most_frequent_value}")

The most frequent value in the Screen column is: 15.6


In [12]:
laptops_df['Screen'] = laptops_df['Screen'].fillna(most_frequent_value)
print(f"The most frequent value in the Screen column is: {most_frequent_value}")

The most frequent value in the Screen column is: 15.6


In [13]:
median_value_1 = laptops_df['Screen'].median()
print(f"the median value of screen is: {median_value}")

the median value of screen is: 15.6


In [14]:
#Has it changed?
#No

In [15]:
# SUM OF WEIGHTS

In [16]:
# Select all Innjoo laptops
innjoo = laptops_df[laptops_df['Brand'] == 'Innjoo']
innjoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [17]:
# Step 2: Select only columns RAM, Storage, Screen.
innjoo[['RAM','Storage','Screen']]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [18]:
# Step 3: Get the underlying NumPy array. Let's call it X.
X = innjoo[['RAM', 'Storage', 'Screen']].to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [19]:
# Step 4: Compute XTX (matrix-matrix multiplication)
XTX = X.T @ X
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [20]:
# Step 5: Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv 

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [21]:
# Step 6: Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [22]:
# Step 7: Multiply inverse of XTX with transpose of X and then by y
w = XTX_inv @ X.T @ y
w

array([45.58076606,  0.42783519, 45.29127938])

In [23]:
# # Step 8: What's the sum of all the elements of the result?
result_sum = np.sum(w)
print(result_sum)

91.2998806299555
